### ISSUE TITLE
Consistency between how views and templates are organized

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/bookwyrm#1465]
The views, templates, and tests should be organized into directories in a way that reflects how they are used. Right now it's a bit of a mishmash. While we're at it, let's improve naming and markup conventions.

- [x] User preferences (#1464)
- [x] Site admin (#1467)
- [x] Directory (#1468)
- [x] User profile (#1469 and #1471)
- [x] User shelves (#1469)
- [x] Create book (#1477)
- [x] Book and editions (#1477)
- [x] Author (#1538)
- [ ] Feeds
- [ ] Discover
- [ ] Lists
- [ ] Get started
- [x] Import (#1600)
- [x] Notifications (#1485)
- [x] Logged out views (landing, login, register, lost password) (#1544)

**Comment by mouse-reeve** [comment]
Closing this because it's overall in a better state
