### ISSUE TITLE
`./bw-dev` should always use `run --rm` for running one-off commands instead of `exec`

### ISSUE THREAD

**Issue by cincodenada** [bookwyrm-social/bookwyrm#1785]
**Describe the bug**
`exec` runs things in a currently-running container (failing if there isn't one), whereas `run --rm` runs things in a temporary instance. Currently `bw-dev` uses `exec` for `initdb` and `update`, both of which cause problems.

In `initdb`, if you're not already running an instance - which, if you're running `initdb`, you're often not - `exec` will fail because there's no instance. `run --rm` will work fine as long as the image is built. In particular,  trying to run the setup instructions through `./bw-dev` will not work (see https://github.com/bookwyrm-social/documentation/pull/51/files)

In `upgrade`, things will usually work, unless you've installed a new requirement that is loaded by `manage.py`. In that case, the old docker image will try to run the new code (since it's mounted into the container), and will crash out with a missing requirement.

**To Reproduce**
Run `./bw-dev initdb` without an instance running already, or run `./bw-dev` upgrade after adding a requirement that's required in the Django startup.

**Expected behavior**
Bookwyrm reinits or upgrades successfully

**Instance**
https://kirja.casa (thanks Stoori!)

**Tasks**

- [x] Use `run --rm` in `update` (#1803)
- [ ] Update `initdb` to `run --rm` (#1804)
- [ ] Update tests to not depend on a running container, probably with `--no-deps`

(This is a note-to-self, ping me if I don't put up a PR this weekend)

**Comment by mouse-reeve** [comment]
The only one this will cause any issue for is the tests. In most cases it's easier and much more intuitive to run the tests with `run --rm`, but  because `run` spins up related images, the tests will always have redis running, so tests that need mocks will pass locally but fail in CI. My process for running tests that need mocks is to use `docker-compose stop` to shut down redis and celery, which lets me `exec` the tests on the web image. 

This is janky and complicated! There is probably a better way to isolate the tests? At any rate, I'm 99% completely all for this change.

**Comment by nycterent** [comment]
also up -d should be used when issuing update command

**Comment by cincodenada** [comment]
> because `run` spins up related images, the tests will always have redis running, so tests that need mocks will pass locally but fail in CI. My process for running tests that need mocks is to use `docker-compose stop` to shut down redis and celery, which lets me `exec` the tests on the web image.

Ah, thank you!! This is a great note, that saves us all some head-scratching I'm sure. I actually just ran across the `--no-deps` flag in `docker-compose` which supposedly prevents it from starting up dependent images, which I think would solve this problem?

Separately, for things like `black` I also had the idea the other day of splitting the `web` image into `web` and, like, `tools` or something - where `web` would only be responsible for running the actual app, and the other image is responsible for things that need the libraries and Django context and such, but not the runtime dependencies (`black`, tests, maybe there's other stuff?) - it might be generally useful to have a way to run commands in the app's environment/context without spinning up a whole stack.

I think for this case though `--no-deps` might do the trick, I'll give that a shot first.

**Comment by mouse-reeve** [comment]
`--no-deps` sounds like the ticket! I like the idea of having a tools image, it does some excessive to run the whole image just for a simple python command.

**Comment by mouse-reeve** [comment]
I've changed the .env settings for the tests such that it's now fine for the tests to run normally with `run --rm` -- and I changed that comand in #1941

**Comment by mouse-reeve** [comment]
Having perused bw-dev, this appears to be fully fixed :)
